# In order to use this solution first run, "python3 -m pip install omsdk"
- name: Full audit of iDRAC interface  # metadata (name of our play)
  hosts: idracs         # maps to inventory
  connection: local     # enable ansible to work with a local library (such as an SDK)
  gather_facts: False   # turn off the first task which is by default an audit

  #pre_tasks:

  tasks:
    # precheck step
    - name: Check on status of iDRAC LC interface
      import_role:
         name: poweredge-lc-interface-status
